# Refer to Hydra documentation for more information about config group defaults.
# - https://hydra.cc/docs/tutorials/basic/your_first_app/defaults/
# - https://hydra.cc/docs/patterns/configuring_experiments/

defaults:
  - datasets: semantic_kitti_dev
  - models: vl-ssc-dev-decoder
  - schedules: adamw_lr2e-4_20e_dev
  - _self_

hydra:
  mode: MULTIRUN  # refer to https://github.com/Lightning-AI/lightning/pull/11617
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M}

trainer:
  devices: 4
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  sync_batchnorm: True
