# @package _global_

data:
  datasets:
    type: SemanticKITTI
    splits: [train, val, test]
    data_root: /public/datasets/SemanticKITTI/
    label_root: /public/datasets/SemanticKITTI/dataset/labels
    depth_root: /public/datasets/SemanticKITTI/dataset/sequences_msnet3d_depth
    frustum_size: 8
    dev: True
  loader:
    batch_size: 1
    num_workers: 4

model:
  channels: 64
  scene_size: [256, 256, 32]
  volume_scale: 2
  num_classes: 20

evaluator:
  type: SSCMetrics
  num_classes: 20
